### ISSUE TITLE
Demo Class Checklist

### ISSUE THREAD

**Issue by vicuk** [vicuk/DAAP-intro-to-github#41]
- [ ] create
- [ ] a branch
- [ ] add some commits
- [ ] open a pull request
- [ ] collaborate with others
- [ ] add additional commits
- [ ] merge branch into master
